const users= [
    {
        "name":"Prelisa",
        "ticket":"0",
        "length":10,
        "breadth":5,
        "hologram":true
    },

    {
        "name":"Ursu",
        "ticket":"1",
        "length":10,
        "breadth":5,
        "hologram":false
    },
    {
        "name":"Deepesh",
        "ticket":"2",
        "length":10,
        "breadth":5,
        "hologram":true
    },
    {
        "name":"Neha",
        "ticket":"3",
        "length":10,
        "breadth":5,
        "hologram":true
    },
    {
        "name":"Eva",
        "ticket":"4",
        "length":10,
        "breadth":5,
        "hologram":false
    },
    {
        "name":"Rajan",
        "ticket":"36",
        "length":10,
        "breadth":5,
        "hologram":false
    },
    {
        "name":"Khags",
        "ticket":"69",
        "length":10,
        "breadth":5,
        "hologram":false
    },
    {
        "name":"Sabin",
        "ticket":"3669",
        "length":10,
        "breadth":5,
        "hologram":false
    },
    {
        "name":"Bibek",
        "ticket":"6",
        "length":10,
        "breadth":5,
        "hologram":false
    }
]
module.exports= users;